### ISSUE TITLE
Add healing items

### ISSUE THREAD

**Issue by ethanmassie** [WIU-Computer-Science-Association/typyboi#5]
This should be a subclass of Item defined in the items.py file.  It needs to add a restorative value to the item(i.e how much the player will be healed by after using the item).  Along with this you should add an action so the player can use healing items.  This action will be similar to the equip_weapon() action.

**Comment by Cadesh** [comment]
Hi, if you allow me, I will work on this one.

**Comment by ethanmassie** [comment]
Hello @Cadesh , thanks for your interest in contributing to the project.  I would like to give members of the WIU Computer Science Association a chance to contribute to some of these issues.  If no one else wants to take on this issue I'll assign it to you in a few days.

**Comment by ethanmassie** [comment]
@Cadesh if you're still interested I've assigned you to this issue.

**Comment by Cadesh** [comment]
Thank you. I will work on it.
